[tool.poetry]
name = "ddl"
version = "0.1.0"
description = ""
authors = ["Maximilian Sander <maximilian_sander@mailbox.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
